---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: test-claim-file
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-iscsi-storage-file
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: test-claim-thin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-iscsi-storage-thin
  resources:
    requests:
      storage: 1Mi