---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    # set this to false if you do not want this storage class to be default
    # storageclass.kubernetes.io/is-default-class: "true"
  name: synology-iscsi-storage-file
provisioner: csi.synology.com
# uncomment below if you want to use different values than the default values
parameters:
  location: '/volume1'
  type: 'FILE'
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    # set this to false if you do not want this storage class to be default
    # storageclass.kubernetes.io/is-default-class: "true"
  name: synology-iscsi-storage-thin
provisioner: csi.synology.com
# uncomment below if you want to use different values than the default values
parameters:
  location: '/volume1'
  type: 'THIN'
reclaimPolicy: Retain